=== Crustan/downunder/src/db/diaries.dtd
<!ELEMENT diaries (diary+)>
	<!ELEMENT diary (creator, entry+)>
		<!ELEMENT creator (#PCDATA)>
		<!ELEMENT entry (author, day, date, place+, text)>
			<!ELEMENT author (#PCDATA)>
				<!ATTLIST author age CDATA #REQUIRED>
			<!ELEMENT day (#PCDATA)>
			<!ELEMENT date (#PCDATA)>
				<!ATTLIST date short CDATA #REQUIRED>
			<!ELEMENT place (city, country)>
				<!ELEMENT city (#PCDATA)>
				<!ELEMENT country (#PCDATA)>
			<!ELEMENT text (#PCDATA)>

=== Crustan/downunder/src/db/diaries.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE diaries SYSTEM "diaries.dtd">

<diaries>
								<!-- ////////////////////////////// ANNS DAGBOK \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ -->
	<diary>
		<creator>Ann</creator>
		<entry>
			<author age="34">Ann</author>
			<day>1</day>
			<date short="001211">11 december 2000</date>
			<place>
				<city>Stockholm</city>
				<country>Sverige</country>
			</place>
			<place>
				<city>Köpenhamn</city>
				<country>Danamrk</country>
			</place>
			<place>
				<city>Singapore</city>
				<country>Singapore</country>
			</place>
			<text>Här satt vi nu på väg till vår drömresa som vi sparat till i nästan 6 år. Barnen är jätteuppspelta då Leffe skjutsar in oss till Arlanda. De vet inte riktigt vad som väntar dem. De ser fram emot att köpa dataspel i Singapore och se lysmaskar i en grotta på Nya Zeeland. Mer vet de nog inte.

På planet till Köpenhamn fick vi frukost. Väl på Kastrup fick vi vänta i två timmar på att vårt plan med Singapore Airlines skulle ta oss vidare mot Singapore. Vi fyra hade en egen rad i mitten av planet. Varje stol hade en TV-skärm framför sig där det var fritt fram att spela Nintendo, PC-spel eller titta på filmer. Christian och Stefan var lite väl klåfingriga med dessa apparater så tyvärr hade två av TV-skärmarna gått sönder redan innan take-off. Jag och Stefan fick vara utan. Problemet nu bestod i att få dessa vildar att sova eftersom vi skulle komma fram till Singapore 6.30. De sov kanske en timme av tolv timmar. Jag och Stefan sov desto mer. Då vi flög över Iran skakade planet något otroligt. Det var just då killarna sov som tur var. Jag själv var alldeles kallsvettig och hade jättestora problem med att inte spy.

Då vi åt lunch på planet var Christian fascinerad av hur glansigt pappret var då man tog bort det från smörpaketet. Man häpnar av lite. De var inte ett dugg förtjusta i maten på planen och de bara spelade TV-spel. Sysselsättningen var helt OK. Resan gick jättebra.
			</text>
		</entry>
		
		<entry>
			<author age="34">Ann</author>
			<day>2</day>
			<date short="001212">12 december 2000</date>
			<place>
				<city>Singapore</city>
				<country>Republiken Singapore</country>
			</place>
			<text>Väl framme i Singapore var vi nu på egen hand. Vi hade tänkt att åka en gratisbuss som gick från flygplanet in till staden och runt där i två timmar, men den gick inte förrän klockan 10:00 så vi tog en taxi istället. Vi åkte in till City och ett hotell som Travel Corner (resebyrå i Åkersberga) brukar anlita (Rendezvous). Taxin blev dyr, 20$, pga två stycken vägtullar à 2$/styck. Hotellet var dyrt (tycker jag), 320$/natt. 
			
			Jaha... nu visste vi inte riktigt vart vi skulle ta vägen. Det var hett och fuktigt och det stank avgaser. Klockan var nu 10.00 och båda barnen stod nästan och sov. Stackarna. Vi gick in på YMCA i närheten och bokade fyra nätter för 120+17$/natt. Skönt, då var hotell för dagarna här på hemresan klart. Vi tog taxi till en krokodilfarm. Där såg vi en show där de bland annat stoppade in huvudet i munnen på en krokodil och pussade den på munnen. Att de vågar! Efter det var vi så trötta och hungriga att vi ville tillbaka till flygplatsens lugna vrå.
			</text>
		</entry>
		
		<entry>
			<author age="34">Ann</author>
			<day>3</day>
			<date short="001213">13 december 2000</date>
			<place>
				<city>Auckland</city>
				<country>Nya Zeeland</country>
			</place>
			<text>Flyg med Singapore Airlines igen. Stefan och jag var så trötta att vi somnade före starten. Stefan sov förbi middagen och killarna blev jätteglada då han inte rörde sin glass. Jag spelade lite TV-spel på planet. Tetris är favoriten nu. Försökte få barnen att sova, men det var inte lätt. När de väl somnat var det svårt att väcka dem framme i Auckland kl 11.25. Vi möttes av skönt soligt väder. Ja, som Sveriges bästa sommardagar ser ut. Jonas hade bokat bil åt oss. Då vi hyrde bilen fick Stefan ta emot ett telefonsamtal i uthyrningsdisken. Där i var Jonas som välkomnade oss hit. 
			
			En orolig men kul bilfärd ca 1 km till hotellet. Där fanns pool. Jippie! Jag satt i solen en timme och fick färg (röd!). Vi åkte in till Auckland med hyrbilen. Allt gick som smort. Jonas hade tipsat oss om att inte åka in till Auckland mellan kl 16-18 pga mycket trafik. Vi åkte in 16.30! Det gick alldeles utmärkt. In i City! Vi åkte upp i City Sky Tower. WOW! 328 m över havet är tornet upp till masten. Det finns betong och pålar 15 m under marken. Det var helt otroligt vilken utsikt över Auckland vi såg. Hamnen, de gamla vulkanerna, etc. Stefan hade svindel, framför allt när Fredrik lutade sig mot fönstret som vette utåt över staden.
			
			Efter tornet gick vi till den välkända kändisrestaurangen Planet Hollywood. Där läste vi om och såg kändisarnas kläder och rekvisita som de haft på sig i olika filmer. Bl.a. såg vi Mad Max motorcykel, Terminatordockan och Freddy Kreugers randiga tröja etc. Stefan åt fajitas, jag åt nachos och barnen åt korv (blä!) och pommes. Hur ska vi få barnen att äta ordentligt under dessa 5 veckor? Idag förbjöd vi hamburgare, imorgon har vi förbjudit pommes.   
			
			&lt;b&gt; DAGENS FUMMEL: &lt;/b&gt;			
			&lt;li&gt;Christian satte sig på pappas solbrillor så att de gick sönder.&lt;/li&gt;
			&lt;li&gt;Pappa lånade Fredriks extra brillor och glömde dem uppe i Sky Tower.&lt;/li&gt;
			&lt;li&gt;Pappa klev på en spik i badrummet och rev sönder hela strumpan.&lt;/li&gt;
			&lt;li&gt;Pappa satte på vindrutetorkarna varje gång han skulle blinka.&lt;/li&gt;
			&lt;li&gt;Pappa skulle flytta bilen på hotellet och hoppade in på passagerarsidan.
			Han klev snabbt ur bilen så att ingen hann se.&lt;/li&gt;
			</text> 
		</entry>
		
		<entry>
			<author age="34">Ann</author>
			<day>4</day>
			<date short="001214">14 december 2000</date>
			<place>
				<city>Waitomo Caves</city>
				<country>Nya Zeeland</country>
			</place>
			<text>Vi vaknade första gången redan vid 5-tiden på morgonen, men åh vad skönt det var att somna om igen. Vi klev upp kl 7 för att käka frukost. Mycket gott. Fredrik åt som om han inte sett mat på flera dagar. 
			
			Kl 9.30 blev det vidare bilfärd till Waitomo Caves där vi skulle se på lysmaskar. Det var en helt otrolig grotta. Fantastiskt att ha varit där. Lysmaskar i taket såg vi också. Hela landskapet runt grottan var väldigt svenskt och vackert (svenskt = midsommaräng). Sedan vidare mot Rotorua dit vi kom fram ca 18.30. Här luktar det konstigt från alla källor med ånga som kommer upp ur jorden. Vi åt en fint upplagd pepparstek/sirloin steak (billig) men tyvärr var den rätt seg. Christian och Fredrik badade i hotellets pool. Hotellets namn: Rydges Rotorua.
			
			&lt;b&gt; DAGENS FUMMEL: &lt;/b&gt;			
			&lt;li&gt;Stefan frågade hotellreceptionisten "Do you do sucker?" när han undrade om killen spelade fotboll.&lt;/li&gt;
			</text>
		</entry>
		
		<entry>
			<author age="34">Ann</author>
			<day>5</day>
			<date short="001215">15 december 2000</date>
			<place>
				<city>Rotorua</city>
				<country>Nya Zeeland</country>
			</place>
			<text>Vi vaknade klockan 7 då vi intog en brakfrukost. Jag har fortfarande aldrig sett barnen äta så mycket. Det är bra, för vi hoppar över lunchen då vi bara tar en glass eller liknande. Vi kom inte iväg från hotellet förrän 10.30 pga alla papper och broschyrer som skulle sorteras och sättas in i pärmar. Stefan tar säkert fem broschyrer på varje ställe vi stannar på. "Kan vara bra att ha", säger han. Jag håller med, men vi har broschyrer överallt.
			
			Idag åkte vi till Hells Gate (Helvetets Port) i Tikitere för att se puttrande lerpölar och ångande berg. Det var otroligt läckert. Leran var så finkornig att den inte kändes när man tog upp den i handen. Dock var inte lukten lika otrolig här i Rotorua. Christian tycker att det stinker surströmming och det ligger ärligt talat inte långt bort.
			
			Efter de underjordiska aktiviteterna åkte vi till Agrodome utanför Rotorua. Där såg vi galna människor som hoppade in i en stor plastbubbla och sedan rullade ner för ett berg. Skithäftigt sa de som gjorde det! I Agrodome såg vi även en fårshow som var både rolig och intressant. Vi såg 19 olika fårraser och fick reda på vad man gjorde med ullen. Fårklippning såg vi också. Världsrekordet är ett får på 30 sekunder. Ett arbetsvärldsrekord är 900 får på en dag vilket betydde ett får/45 sek (wow!). Vi såg också vallhundar in action. Med hjälp av visslingar så går hunden till höger/vänster eller är stilla. Det här skulle mamma ha sett. En vallhund var en korsning av bordercollie/blodhund och labrador(?).
			
			Senare åkte Stefan, Christian och Fredrik upp i en helikopter över Rotorua. Jag var för snål så jag hoppade över det äventyret. Tillbaka till hotellet så hoppade vi i poolen till barnens förtjusning. 21.30 somnade 75% av familjen. Jag somnade 22.15. SKÖNT!
			 
			&lt;b&gt; DAGENS FUMMEL: &lt;/b&gt;			
			&lt;li&gt;Christian glömde kepsen på restaurang Zizzler.&lt;/li&gt; 
			</text>
		</entry>
		
		<entry>
			<author age="34">Ann</author>
			<day>6</day>
			<date short="001216">16 december 2000</date>
			<place>
				<city>Napier</city>
				<country>Nya Zeeland</country>
			</place>
			<text>Upp och hoppa klockan 07.00. Alla var pigga. Ännu en brakfrukost åkte ner i våra magar. Fredrik åt bland annat fyra kiwifrukter. De, och ananasen, är ju så goda här. Grabbarna blev rätt glada då vi lämnade stanken i Rotorua. Det första stoppet blev på Huka Falls. Det var ett mäktigt vattenfall med klarblått vatten. Man fick ut elektricitet ur fallet till hushållen i Napier. Vi stannade på ytterligare ett ställe där det fanns vattenfall i en ravin. Otroligt! Där träffade vi på en nyzeeländsk familj som förstod vad vi sa. De bodde i Napier och frun var från Danmark. Hon hade bott här i 15 år. Det är konstigt hur landskapet ändrar sig hela tiden. Berg och dalar. Barrträd och lövträd blandat med palmer överallt. Vägen från Rotorua till Huka var översållad med gulgingst. Jättevackert.
